module BinLoader
  extend self

  LOCAL_BIN = %w[bin/mrsk bin/kamal].freeze
  BUNDLER_COMMENT = "This file was generated by Bundler"

  def load_local_bin
    original_cwd = Dir.pwd

    loop do
      if (bin = find_executable)
        exec bin, *ARGV
      end

      # If we exhaust the search there is no executable, run bundled kamal from original cwd
      Dir.chdir(original_cwd) && return if Pathname.new(Dir.pwd).root?

      # Otherwise keep moving upwards in search of an executable.
      Dir.chdir("..")
    end
  end

  private

  def find_executable
    LOCAL_BIN.each do |bin|
      if File.exist?(bin) && File.executable?(bin) && File.read(bin, 300).include?(BUNDLER_COMMENT)
        return bin
      end
    end

    nil
  end
end
